---
services:
  database:
    image: mounikaaarepu/pyapp:database_image
    deploy:
      replicas: 1
    ports:
      - "3306:3306"  
    networks:
      - mynetwork  


  auth:
    image: mounikaaarepu/pyapp:auth_image
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    depens_on:
      - database


  book:
    image: mounikaaarepu/pyapp:book_image
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    depens_on:
      - database


  borrow:
    image: mounikaaarepu/pyapp:borrow_image
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    networks:
      - mynetwork
    depens_on:
      - database

  frontend:
    image: mounikaaarepu/pyapp:frontend
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    depens_on:
      - auth
      - book
      - borrow

networks:
  mynetwork:
    driver: overlay
